# Generated by Django 4.2.30 on 2026-04-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('materia', models.CharField(max_length=200, verbose_name='Materia')),
                ('fecha', models.DateField(verbose_name='Fecha de asistencia')),
            ],
            options={
                'verbose_name': 'registro de asistencia',
                'verbose_name_plural': 'registros de asistencia',
                'ordering': ['-fecha', 'apellido', 'nombre'],
            },
        ),
    ]
