# Generated by Django 4.2.30 on 2026-04-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroasistencia',
            name='materia',
        ),
    ]
